# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMatchingList <- function(uids, counts, location) {
    .Call('geneticsCRE_getMatchingList', PACKAGE = 'geneticsCRE', uids, counts, location)
}

ProcessPaths <- function(r_src_uids1, r_trg_uids1, r_count_locs1, r_signs1, r_src_uids1_2, r_trg_uids1_2, r_count_locs1_2, r_signs1_2, r_src_uids2, r_trg_uids2, r_count_locs2, r_signs2, r_src_uids3, r_trg_uids3, r_count_locs3, r_signs3, r_src_uids4, r_trg_uids4, r_count_locs4, r_signs4, r_src_uids5, r_trg_uids5, r_count_locs5, r_signs5, r_data_inds1, r_data_inds1_2, r_data_inds2, r_data_inds3, r_data1, r_data2, r_value_table, num_cases, num_ctrls, top_k, iterations, r_perm_cases, method, path_length, nthreads) {
    .Call('geneticsCRE_ProcessPaths', PACKAGE = 'geneticsCRE', r_src_uids1, r_trg_uids1, r_count_locs1, r_signs1, r_src_uids1_2, r_trg_uids1_2, r_count_locs1_2, r_signs1_2, r_src_uids2, r_trg_uids2, r_count_locs2, r_signs2, r_src_uids3, r_trg_uids3, r_count_locs3, r_signs3, r_src_uids4, r_trg_uids4, r_count_locs4, r_signs4, r_src_uids5, r_trg_uids5, r_count_locs5, r_signs5, r_data_inds1, r_data_inds1_2, r_data_inds2, r_data_inds3, r_data1, r_data2, r_value_table, num_cases, num_ctrls, top_k, iterations, r_perm_cases, method, path_length, nthreads)
}

