# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProcessPaths <- function(srcuids1, trguids1, uids_CountLoc1, joining_gene_sign1, srcuids1_2, trguids1_2, uids_CountLoc1_2, joining_gene_sign1_2, srcuids2, trguids2, uids_CountLoc2, joining_gene_sign2, srcuids3, trguids3, uids_CountLoc3, joining_gene_sign3, srcuids4, trguids4, uids_CountLoc4, joining_gene_sign4, srcuids5, trguids5, uids_CountLoc5, joining_gene_sign5, data_inds1, data_inds1_2, data_inds2, data_inds3, data, data2, ValueTable, nCases, nControls, K, iterations, CaseORControl, method, pathLength, nthreads) {
    .Call('geneticsCRE_ProcessPaths', PACKAGE = 'geneticsCRE', srcuids1, trguids1, uids_CountLoc1, joining_gene_sign1, srcuids1_2, trguids1_2, uids_CountLoc1_2, joining_gene_sign1_2, srcuids2, trguids2, uids_CountLoc2, joining_gene_sign2, srcuids3, trguids3, uids_CountLoc3, joining_gene_sign3, srcuids4, trguids4, uids_CountLoc4, joining_gene_sign4, srcuids5, trguids5, uids_CountLoc5, joining_gene_sign5, data_inds1, data_inds1_2, data_inds2, data_inds3, data, data2, ValueTable, nCases, nControls, K, iterations, CaseORControl, method, pathLength, nthreads)
}

getMatchingList <- function(uids, counts, location) {
    .Call('geneticsCRE_getMatchingList', PACKAGE = 'geneticsCRE', uids, counts, location)
}

